### ISSUE TITLE
add mention of TypeScript typings in this repo

### ISSUE THREAD

**Issue by jgravois** [Esri/arcgis-to-geojson-utils#11]
now that @jeffJacobson has gotten his typings landed in DefinitelyTyped, lets make sure to promote them here.

**Comment by jgravois** [comment]
1f2957f529597d8b6897fb31297cb23d444acddd

**Comment by JeffJacobson** [comment]
Those typings can now be accessed via the NPM repository: [@types/arcgis-to-geojson-utils](https://www.npmjs.com/package/@types/arcgis-to-geojson-utils). (The publication to NPM is the result of an automated process, but it didn't occur immediately after my contribution, which is why I'm only mentioning it now.)

I have found that Typescript's [module resolution](http://www.typescriptlang.org/docs/handbook/module-resolution.html#node) configuration setting should be set to `node` in order for the compiler to recognize the types.
