### ISSUE TITLE
no 'dist' folder created when running 'npm install arcgis-to-geojson-utils' on commandline

### ISSUE THREAD

**Issue by jgravois** [Esri/arcgis-to-geojson-utils#3]
why is `npm run bundle` called for `arcgis-to-geojson-utils` after its installed via the dependency [here](https://github.com/patrickarlt/esri-leaflet/blob/breakout-geojson-tools/package.json#L14), but the same script is **not** run when the package is installed via the commandline?

```
$ npm install arcgis-to-geojson-utils
```

i haven't been able to figure out how to use the module when its still native ES6.

**Comment by patrickarlt** [comment]
Looks like I need an empty `.npmignore` file otherwise the `.gitignore` removes `dist` from the published version.

I'm doing these a little differently than Esri Leaflet. In Esri Leaflet we ship ES6 with directions for every compiler/toolchain/whatever on how to compile it. This was a great experiment and I'm glad it worked but it is in general a total mess. It is way easier to do what I am doing here and ship compiled code with a special `jspm` directive for ES6.

**Comment by jgravois** [comment]
:bulb: makes a **lot** more sense now.

> In Esri Leaflet we ship ES6 ... it is in general a total mess

agreed!

**Comment by jgravois** [comment]
try running [`npm pack`](https://docs.npmjs.com/cli/pack) before publishing `1.0.1` to confirm that the .zip is gone and the 'dist' folder is there.

**Comment by patrickarlt** [comment]
Looks like we should be good now.

**Comment by jgravois** [comment]
confirmed.  thanks!
