### ISSUE TITLE
Not able to use arcgis-to-geojson-utils Typings successfully 

### ISSUE THREAD

**Issue by amrutab4** [Esri/arcgis-to-geojson-utils#32]
Hi , 
I am setting up a typescript application and it's structure looks like this:
![image](https://user-images.githubusercontent.com/38122484/39516800-a1e42830-4e1b-11e8-8843-ca6103550a90.png)

Typings file looks like this:
![image](https://user-images.githubusercontent.com/38122484/39516829-bb7065c0-4e1b-11e8-9af7-6d6c5514857d.png)

Package.json looks like this:
![image](https://user-images.githubusercontent.com/38122484/39516865-d294c020-4e1b-11e8-970d-25dc11f531bc.png)

When I am running the application, I am getting this error:
![image](https://user-images.githubusercontent.com/38122484/39516916-f3b73f80-4e1b-11e8-9e4e-77c5b3b9f284.png)

I am not sure, how the code is trying to access the arcgis-to-geojson utils from ArcGIS JS API even when declaration files are mentioned in typings.d.ts

I am new to typescript and not sure if I am doing something wrong here.

Thanks and Regards,
Amruta

**Comment by amrutab4** [comment]
@jgravois and @JeffJacobson I am kinda stuck where in this setting up Type script application, I am working with ArcGIS JS API typings and ArcGIS-geojson utils typings and facing issues with ArcGIS geojson utils typings. Can you help me please?

**Comment by JeffJacobson** [comment]
The issue isn't with typings. If you've run `tsc` and didn't get any error messages, then the typings are working correctly.

The issue is with the configuration of the Dojo framework and the ArcGIS JavaScript API. You'll need to configure the *packages* setting of the [dojoConfig](https://dojotoolkit.org/documentation/tutorials/1.10/dojo_config/) variable to tell the framework where to find the `arcgis-to-geojson-utils.js` file.

I don't think you need that `typings.d.ts` file. By default, TypeScript will automatically recognize the types in the node_modules/@types folder. (If you have additional type definition files that aren't in the same location as the rest of your source, you can specify these locations in the tsconfig.json file.)

As for *dojo-typings*, I've never been able to get that to work. I'm not sure if it is compatible with the 2.x versions of TypeScript.

**Comment by amrutab4** [comment]
@JeffJacobson Thanks for pointing me to the right cause. Typings are working fine! I made it work with dojo-typings somehow but we may not use dojo-typings in future.
once again Thank you so much for your help!
