### ISSUE TITLE
Need help with 2.2 version Typings 

### ISSUE THREAD

**Issue by amrutab4** [Esri/arcgis-to-geojson-utils#33]
Hi,

There are 2 dependencies for @types/arcgis-to-geojson-utils:
@types/arcgis-rest-api 
https://www.npmjs.com/package/%40types%2Farcgis-rest-api
 @types/geojson
https://www.npmjs.com/package/%40types%2Fgeojson

I am working with project which is having Typescript version 2.2. and this version is kind of frozen for the project :(
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/geojson/index.d.ts 
This file is giving error as it is using Typescript version 2.3

Can I get typings for 2.2 version anywhere? :(
As even '@types/arcgis-rest-api' is working fine on Ts version 2.2

Can anybody help? Where I can get 2.2 Typings?

Thanks and Regards,
Amruta

**Comment by jgravois** [comment]
looking at the documentation for [TypeScript 2.3](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-3.html), it doesn't appear that _any_ of the language features that were introduced are being utilized in the typings for `geojson`.

that said, you're asking a generic TypeScript question, and its not even about the typings for this library, but rather one of its dependencies. because of this, you're better off researching/posting on Stack Overflow or some other forum than relying on the assistance of the 14 people that subscribe to updates from _this_ repo.

best of luck.
